# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Katpins Portfolio
email: kateryna.pinchuks@gmail.com
linkedin: https://www.linkedin.com/in/kateryna-pinchuk-595432193/
github: https://github.com/Katpins
itchio: https://katpinss.itch.io/

about: Hi! My name is Katja and I am a junior game developer open for feedback and improvement. Passionate about the medium of video games and with interest in technical and visual side of the art. I am ready to take on new challenges and grow above myself.

description: >- # this means to ignore newlines until "baseurl:"
  Junior developer open for feedback and improvement.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

collections:
  skills:
    output: true
  projects:
    output: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
